apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: webtoon
  namespace: argocd
  labels:
    app: webtoon
spec:
  project: default
  source:
    path: k8s/apps/webtoon
    repoURL: https://github.com/gastbob40/infrastructure.git
    targetRevision: old
  destination:
    name: in-cluster
    namespace: webtoon
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
