apiVersion: batch/v1
kind: CronJob
metadata:
  name: frat-dump
spec:
  schedule: "0 */6 * * *" # every 6 hours
  successfulJobsHistoryLimit: 0
  jobTemplate:
    spec:
      template:
        spec:
          restartPolicy: OnFailure
          containers:
            - name: app
              image: systemfraternity/frat_dump
              imagePullPolicy: Always
              command:
                - python
                - manage.py
                - dump
              env:
                - name: POD_METADATA_UID
                  valueFrom:
                    fieldRef:
                      fieldPath: metadata.uid
                - name: DB_NAME
                  value: frat_dump
                - name: DB_USER
                  valueFrom:
                    secretKeyRef:
                      name: fraternity.frat-dump.infra-main-cluster.credentials.postgresql.acid.zalan.do
                      key: username
                - name: DB_PASSWORD
                  valueFrom:
                    secretKeyRef:
                      name: fraternity.frat-dump.infra-main-cluster.credentials.postgresql.acid.zalan.do
                      key: password
              envFrom:
                - configMapRef:
                    name: common-config
              ports:
                - name: http
                  containerPort: 8000
                  protocol: TCP
              volumeMounts:
                - mountPath: /app/media/dumps
                  name: media-volume
          securityContext:
            fsGroup: 2000
          volumes:
            - name: media-volume
              persistentVolumeClaim:
                claimName: frat-dump-pvc-media
