---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: frat-dump
spec:
  replicas: 1
  selector:
    matchLabels:
      component: frat-dump
  template:
    metadata:
      labels:
        component: frat-dump
    spec:
      nodeSelector:
        node-role.kubernetes.io/master: "true"
      containers:
        - name: app
          image: systemfraternity/frat_dump
          imagePullPolicy: Always
          env:
            - name: POD_METADATA_UID
              valueFrom:
                fieldRef:
                  fieldPath: metadata.uid
            - name: DB_NAME
              value: frat_dump
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: fraternity.frat-dump.infra-main-cluster.credentials.postgresql.acid.zalan.do
                  key: username
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: fraternity.frat-dump.infra-main-cluster.credentials.postgresql.acid.zalan.do
                  key: password
          envFrom:
            - configMapRef:
                name: common-config
          ports:
            - name: http
              containerPort: 8000
              protocol: TCP
          volumeMounts:
            - mountPath: /app/media/dumps
              name: media-volume
      securityContext:
        fsGroup: 2000
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - weight: 100
              podAffinityTerm:
                labelSelector:
                  matchExpressions:
                    - key: app
                      operator: In
                      values:
                        - frat-dump
                    - key: component
                      operator: In
                      values:
                        - frat-dump
                topologyKey: kubernetes.io/hostname
      volumes:
        - name: media-volume
          persistentVolumeClaim:
            claimName: frat-dump-pvc-media
