---
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: default-issuer
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    email: gastbob40@gmail.com
    privateKeySecretRef:
      name: default-issuer
    solvers:
      - http01:
          ingress:
            ingressClassName: public
