---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: "cocfc-clash-moderation"
  namespace: "cocfr"
  annotations:
    cert-manager.io/cluster-issuer: default-issuer
    cert-manager.io/revision-history-limit: "1"
    nginx.ingress.kubernetes.io/rewrite-target: /$2

spec:
  ingressClassName: public
  rules:
    - host: "cocfr.gastbob40.com"
      http:
        paths:
          - path: /api(/|$)(.*)
            pathType: ImplementationSpecific
            backend:
              service:
                name: "cocfc-clash-moderation"
                port:
                  number: 8080
  tls:
    - hosts:
        - "cocfr.gastbob40.com"
      secretName: "cocfr.gastbob40.com-tls"