---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: pg-glacier
  namespace: postgres
spec:
  schedule: "0 2 * * 1"
  successfulJobsHistoryLimit: 0
  failedJobsHistoryLimit: 0
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: pg-backup
              image: gastbob40/postgres-backup:latest
              command: [ "/usr/local/bin/glacier.sh" ]
              imagePullPolicy: Always
              env:
                # Secret for local Minio
                - name: AWS_ACCESS_KEY_ID_PRIVATE
                  valueFrom:
                    secretKeyRef:
                      name: minio-secrets
                      key: root-user
                - name: AWS_SECRET_ACCESS_KEY_PRIVATE
                  valueFrom:
                    secretKeyRef:
                      name: minio-secrets
                      key: root-password
                - name: AWS_ENDPOINT_S3_PRIVATE
                  value: "https://api.s3.gastbob40.ovh"

                # Secret for AWS Glacier
                - name: AWS_ACCESS_KEY_ID_GLACIER
                  valueFrom:
                    secretKeyRef:
                      name: aws-secrets
                      key: AWS_ACCESS_KEY_ID

                - name: AWS_SECRET_ACCESS_KEY_GLACIER
                  valueFrom:
                    secretKeyRef:
                      name: aws-secrets
                      key: AWS_SECRET_ACCESS_KEY
                - name: AWS_REGION_GLACIER
                  valueFrom:
                    secretKeyRef:
                      name: aws-secrets
                      key: AWS_REGION
                - name: AWS_BUCKET_GLACIER
                  valueFrom:
                    secretKeyRef:
                      name: aws-secrets
                      key: AWS_BUCKET
          restartPolicy: OnFailure