---
apiVersion: ricoberger.de/v1alpha1
kind: VaultSecret
metadata:
  name: minio-secrets
  namespace: postgres
spec:
  path: k8s/minio
  keys:
    - root-user
    - root-password
  type: Opaque

---

apiVersion: ricoberger.de/v1alpha1
kind: VaultSecret
metadata:
  name: aws-secrets
  namespace: postgres
spec:
  path: k8s/amazon
  keys:
    - AWS_ACCESS_KEY_ID
    - AWS_SECRET_ACCESS_KEY
    - AWS_BUCKET
    - AWS_REGION
  type: Opaque
