---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: cocfc-clash-birthday
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      component: cocfc-clash-birthday
  template:
    metadata:
      labels:
        component: cocfc-clash-birthday
    spec:
      containers:
        - name: app
          image: gastbob40/clash-birthday
          imagePullPolicy: Always
          env:
            - name: POD_METADATA_UID
              valueFrom:
                fieldRef:
                  fieldPath: metadata.uid
            - name: DATASOURCE_HOST
              value: infra-main-cluster.postgres.svc.cluster.local
            - name: DATASOURCE_DB
              value: clash_birthday
            - name: DATASOURCE_USERNAME
              valueFrom:
                secretKeyRef:
                  name: cocfr.clash-birthday.infra-main-cluster.credentials.postgresql.acid.zalan.do
                  key: username
            - name: DATASOURCE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: cocfr.clash-birthday.infra-main-cluster.credentials.postgresql.acid.zalan.do
                  key: password
            - name: DISCORD_TOKEN
              valueFrom:
                secretKeyRef:
                  name: cocfr-clash-birthday-secrets
                  key: DISCORD_TOKEN
            - name: BIRTHDAY_CHANNEL_ID
              valueFrom:
                secretKeyRef:
                  name: cocfr-clash-birthday-secrets
                  key: BIRTHDAY_CHANNEL_ID
            - name: BIRTHDAY_ADMIN_IDS
              valueFrom:
                secretKeyRef:
                  name: cocfr-clash-birthday-secrets
                  key: BIRTHDAY_ADMIN_IDS
            - name: BIRTHDAY_GUILD_ID
              valueFrom:
                secretKeyRef:
                  name: cocfr-clash-birthday-secrets
                  key: BIRTHDAY_GUILD_ID
            - name: BIRTHDAY_ROLE_ID
              valueFrom:
                secretKeyRef:
                  name: cocfr-clash-birthday-secrets
                  key: BIRTHDAY_ROLE_ID
          envFrom:
            - configMapRef:
                name: common-config
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
