---
kind: Kustomization

commonLabels:
  component: cocfr

configMapGenerator:
  - name: common-config
    literals:
      - DB_HOST=infra-main-cluster.postgres.svc.cluster.local

resources:
  - deployment.yml
  - secrets.yml

