---
apiVersion: ricoberger.de/v1alpha1
kind: VaultSecret
metadata:
  name: climradar-stock-watch-secrets
  namespace: climradar
spec:
  path: k8s/climradar/stock-watch
  keys:
    - FREE_SMS_USER
    - FREE_SMS_PASS
  type: Opaque
