---
apiVersion: ricoberger.de/v1alpha1
kind: VaultSecret
metadata:
  name: minio-secrets
  namespace: meal-planner
spec:
  path: k8s/minio
  keys:
    - root-user
    - root-password
  type: Opaque

---
apiVersion: ricoberger.de/v1alpha1
kind: VaultSecret
metadata:
  name: meal-planner-backend-secrets
  namespace: meal-planner
spec:
  path: k8s/meal-planner/backend
  keys:
    - HELLOFRESH_USERNAME
    - HELLOFRESH_PASSWORD
  type: Opaque
