---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: "meal-planner-frontend"
  namespace: "meal-planner"
  annotations:
    cert-manager.io/cluster-issuer: default-issuer
    cert-manager.io/revision-history-limit: "1"

spec:
  ingressClassName: traefik
  rules:
    - host: "meal-planner.gastbob40.com"
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: "meal-planner-frontend"
                port:
                  number: 3000
  tls:
    - hosts:
        - "meal-planner.gastbob40.com"
      secretName: "meal-planner.gastbob40.com-tls"

