---
apiVersion: ricoberger.de/v1alpha1
kind: VaultSecret
metadata:
  name: meal-planner-frontend-secrets
  namespace: meal-planner
spec:
  path: k8s/meal-planner/frontend
  keys:
    - next-auth-secret
  type: Opaque
