---
kind: Kustomization
namespace: fraternity

resources:
  - namespace.yml
  - frat-shop
  - fraternity-api
  - discord-presence

configMapGenerator:
  - name: common-config
    literals:
      - DB_HOST=infra-main-cluster.postgres.svc.cluster.local
