---
kind: Kustomization
namespace: fraternity

resources:
  - namespace.yml
  - frat-logs
  - frat-shop

configMapGenerator:
  - name: common-config
    literals:
      - DB_HOST=infra-main-cluster.postgres.svc.cluster.local
