---
apiVersion: ricoberger.de/v1alpha1
kind: VaultSecret
metadata:
  name: discord-presence-secrets
  namespace: fraternity
spec:
  path: k8s/fraternity/discord-presence
  keys:
    - FRATERNITY_BOT_TOKEN
    - FRATWORLD_BOT_TOKEN
  type: Opaque
