---
apiVersion: ricoberger.de/v1alpha1
kind: VaultSecret
metadata:
  name: fraternity-api-secrets
  namespace: fraternity
spec:
  path: k8s/fraternity/fraternity-api
  keys:
    - OAUTH_DISCORD_CLIENT_ID
    - OAUTH_DISCORD_CLIENT_SECRET
    - SESSION_SECRET
  type: Opaque
