---
kind: Kustomization
namespace: epimac

commonLabels:
  app: fleet

resources:
  - namespace.yml
  - fleet-front
  - operator

images:
  - name: gastbob40/epimac-fleet
    newTag: latest
  - name: gastbob40/operator
    newTag: latest