namespace: argocd

resources:
  - namespace.yml
  - https://raw.githubusercontent.com/argoproj/argo-cd/v2.12.4/manifests/install.yaml

patchesStrategicMerge:
  - argocd-deployment.yml

patches:
  - target:
      kind: ConfigMap
      name: argocd-cmd-params-cm
    path: argocd-cmd-params-patch.yml
