---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: byparr
  namespace: byparr
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: byparr
  template:
    metadata:
      labels:
        app: byparr
    spec:
      containers:
        - name: byparr
          image: ghcr.io/thephaseless/byparr:latest
          imagePullPolicy: Always
          ports:
            - name: http
              containerPort: 8191
              protocol: TCP