---
apiVersion: v1
kind: Service
metadata:
  name: byparr
  namespace: byparr
spec:
  type: ClusterIP
  selector:
    app: byparr
  ports:
    - name: http
      port: 8191
      targetPort: http
      protocol: TCP