name: ci

on:
  push:
    branches:
      - 'main'

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Download Pluto
        uses: FairwindsOps/pluto/github-action@master

      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 2

      - name: Use pluto
        run: |
          mkdir -p pluto-results
          pluto detect-files -d ./k8s --output wide > pluto-results/pluto-report.txt
          echo "Pluto Report:" && cat pluto-results/pluto-report.txt

      - name: Upload Pluto Report as Artifact
        uses: actions/upload-artifact@v4
        with:
          name: pluto-deprecation-report
          path: pluto-results/pluto-report.txt


      - name: Check if dockers/postgres-backup was modified
        id: check_changes
        run: |
          if git diff --name-only HEAD~1 | grep -q '^dockers/postgres-backup/'; then
            echo "changes_detected=true" >> $GITHUB_ENV
          else
            echo "changes_detected=false" >> $GITHUB_ENV
          fi

      - name: Set up QEMU
        if: env.changes_detected == 'true'
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        if: env.changes_detected == 'true'
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        if: env.changes_detected == 'true'
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        if: env.changes_detected == 'true'
        uses: docker/build-push-action@v6
        with:
          push: true
          tags: gastbob40/postgres-backup:latest
          context: dockers/postgres-backup
          platforms: linux/amd64,linux/arm64