apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: chronodrive-proxy
spec:
  podSelector:
    matchLabels:
      component: chronodrive-proxy
  policyTypes: [Ingress]
  ingress:
    - from:
        - podSelector:
            matchLabels:
              component: meal-planner-api
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: flaresolverr
          podSelector:
            matchLabels:
              app.kubernetes.io/instance: flaresolverr
              app.kubernetes.io/name: flaresolverr
      ports:
        - protocol: TCP
          port: 1055
