apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argocd-deployment
  namespace: argocd
spec:
  project: default
  source:
    path: k8s/cluster/argocd-deployment
    repoURL: https://github.com/gastbob40/infrastructure.git
    
  destination:
    namespace: argocd-deployment
    name: in-cluster
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
