---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: byparr
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  labels:
    app: byparr
spec:
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      prune: true
  destination:
    name: in-cluster
    namespace: byparr
  project: default
  source:
    repoURL: https://github.com/gastbob40/infrastructure.git
    targetRevision: main
    path: k8s/cluster/byparr