---
apiVersion: v1
kind: Namespace
metadata:
  name: flannel
  labels:
    pod-security.kubernetes.io/enforce: privileged

---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: flannel
  namespace: argocd
spec:
  project: default
  destination:
    namespace: flannel
    name: in-cluster
  syncPolicy:
    automated: {}
  source:
    repoURL: https://flannel-io.github.io/flannel
    chart: flannel
    targetRevision: v0.26.3
    helm:
      values: |
        podCidr: 10.42.0.0/16
