apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: github-actions
  namespace: argocd
spec:
  project: default
  source:
    path: k8s/cluster/github-actions
    repoURL: https://github.com/gastbob40/infrastructure.git
    targetRevision: old
  destination:
    namespace: github-actions
    name: in-cluster
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
