apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ingress-nginx
  namespace: argocd
spec:
  project: default
  destination:
    namespace: ingress-nginx
    name: in-cluster
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
  source:
    repoURL: https://kubernetes.github.io/ingress-nginx
    chart: ingress-nginx
    targetRevision: 4.12.1
    helm:
      values: |
        controller:
          # kind: DaemonSet
        
          nodeSelector:
            node-role.kubernetes.io/master: "true"
        
          ingressClass: public
          ingressClassResource:
            name: public
            default: true
        
          config:
            allow-snippet-annotations: "true"
            real-ip-header: "X-Forwarded-For"
            forwarded-for-header: "X-Forwarded-For"
            real-ip-recursive: "true"
            compute-full-forwarded-for: "true"
            use-forwarded-headers: "true"
            set-real-ip-from: "0.0.0.0/0"
          service:
            externalTrafficPolicy: Local
