apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ingress-nginx
  namespace: argocd
spec:
  project: default
  destination:
    namespace: ingress-nginx
    name: in-cluster
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
  source:
    repoURL: https://kubernetes.github.io/ingress-nginx
    chart: ingress-nginx
    targetRevision: 4.12.0
    helm:
      values: |
        controller:
          ingressClass: public
          ingressClassResource:
            name: public
            default: true
          config:
            allow-snippet-annotations: "true"
            enable-real-ip: "true"
            forwarded-for-header: "true"
          service:
            annotations:
              kubernetes.civo.com/loadbalancer-enable-proxy-protocol: send-proxy
            externalTrafficPolicy: Local
