apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ingress-nginx
  namespace: argocd
spec:
  project: default
  destination:
    namespace: ingress-nginx
    name: in-cluster
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
  revisionHistoryLimit: 2
  source:
    repoURL: https://kubernetes.github.io/ingress-nginx
    chart: ingress-nginx
    targetRevision: 4.13.2
    helm:
      values: |
        controller:
          kind: Deployment
          replicaCount: 1
          revisionHistoryLimit: 0
          
          strategy:
            type: Recreate

          nodeSelector:
            kubernetes.io/hostname: k8s-master
          
          tolerations:
            - key: "node-role.kubernetes.io/master"
              operator: "Exists"
              effect: "NoSchedule"
        
          ingressClass: public
          ingressClassResource:
            name: public
            default: true
        
          terminationGracePeriodSeconds: 30
          
          extraArgs:
            profiler-port: 0
          
          config:
            allow-snippet-annotations: "true"
            real-ip-header: "X-Forwarded-For"
            forwarded-for-header: "X-Forwarded-For"
            real-ip-recursive: "true"
            compute-full-forwarded-for: "true"
            use-forwarded-headers: "true"
            enable-real-ip: "true"
            proxy-add-original-uri-header: "true"
          service:
            type: LoadBalancer
