---
apiVersion: ricoberger.de/v1alpha1
kind: VaultSecret
metadata:
  name: minio-secrets
  namespace: minio
spec:
  path: k8s/minio
  keys:
    - root-user
    - root-password
  type: Opaque

---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: minio
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  labels:
    app: minio
spec:
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      prune: true
  destination:
    name: in-cluster
    namespace: minio
  project: default
  source:
    repoURL: registry-1.docker.io/bitnamicharts
    targetRevision: 17.0.19
    chart: minio
    helm:
      values: |
        extraEnvVars:
          - name: MINIO_BROWSER_REDIRECT_URL
            value: https://s3.gastbob40.ovh
          - name: MINIO_SERVER_URL
            value: https://api.s3.gastbob40.ovh
          - name: MINIO_ROOT_USER
            valueFrom:
              secretKeyRef:
                name: minio-secrets
                key: root-user
          - name: MINIO_ROOT_PASSWORD
            valueFrom:
              secretKeyRef:
                name: minio-secrets
                key: root-password
        auth:
          existingSecret: "minio-secrets"
        # Configuration pour l'API MinIO (S3)
        ingress:
          enabled: true
          ingressClassName: "public"
          hostname: api.s3.gastbob40.ovh
          pathType: Prefix
          annotations:
            cert-manager.io/cluster-issuer: default-issuer
            cert-manager.io/revision-history-limit: "1"
            nginx.ingress.kubernetes.io/proxy-body-size: "4G"
          tls: true
        # Configuration pour la Console UI (séparée depuis v17.0.0)
        console:
          enabled: true
          ingress:
            enabled: true
            ingressClassName: "public"
            hostname: s3.gastbob40.ovh
            pathType: Prefix
            annotations:
              cert-manager.io/cluster-issuer: default-issuer
              cert-manager.io/revision-history-limit: "1"
              nginx.ingress.kubernetes.io/proxy-body-size: "4G"
            tls: true
        persistence:
          size: 50Gi
        nodeSelector:
          node-role.kubernetes.io/master: "true"
          
