apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: postgres
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io

spec:
  project: default
  source:
    path: k8s/cluster/postgres
    repoURL: https://github.com/gastbob40/infrastructure.git
    
  destination:
    namespace: postgres
    name: in-cluster
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
