apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: redpanda
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://charts.redpanda.com
    targetRevision: 25.1.1
    chart: redpanda
    helm:
      values: |
        nodeSelector:
          node-role.kubernetes.io/master: "true"
        statefulset:
          replicas: 1
        listeners:
          kafka:
            tls:
              enabled: false

  destination:
    namespace: redpanda
    name: in-cluster
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      prune: true

---

apiVersion: ricoberger.de/v1alpha1
kind: VaultSecret
metadata:
  name: redpanda-secrets
  namespace: redpanda
spec:
  path: k8s/redpanda
  keys:
    - auth
  type: Opaque

---

apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: redpanda-console-ingress
  namespace: redpanda
  annotations:
    cert-manager.io/cluster-issuer: default-issuer
    cert-manager.io/revision-history-limit: "1"
    nginx.ingress.kubernetes.io/auth-type: "basic"
    nginx.ingress.kubernetes.io/auth-secret: "redpanda-secrets"
    nginx.ingress.kubernetes.io/auth-realm: "Authentication Required"

spec:
  ingressClassName: public
  rules:
    - host: "kafka-console.gastbob40.ovh"
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: "redpanda-console"
                port:
                  number: 8080
  tls:
    - hosts:
        - "kafka-console.gastbob40.ovh"
      secretName: "redpanda-console-tls"
