apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: uptime-kuma
  namespace: argocd
spec:
  project: default
  source:
    path: k8s/cluster/uptime-kuma
    repoURL: https://github.com/gastbob40/infrastructure.git
    targetRevision: HEAD
  destination:
    namespace: uptime-kuma
    name: in-cluster
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
