apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: vault-secrets-operator
  namespace: argocd
spec:
  project: default
  destination:
    namespace: vault-secrets-operator
    name: in-cluster
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
  source:
    repoURL: https://ricoberger.github.io/helm-charts
    chart: vault-secrets-operator
    targetRevision: 2.7.0
    helm:
      values: |
        vault:
          authMethod: approle
          appRolePath: auth/k8s
          reconciliationTime: 60
          address: https://vault.k8s.gastbob40.ovh
        environmentVars:
          - name: VAULT_ROLE_ID
            valueFrom:
              secretKeyRef:
                name: vault-approle
                key: VAULT_ROLE_ID
          - name: VAULT_SECRET_ID
            valueFrom:
              secretKeyRef:
                name: vault-approle
                key: VAULT_SECRET_ID
          - name: VAULT_TOKEN_MAX_TTL
            valueFrom:
              secretKeyRef:
                name: vault-approle
                key: VAULT_TOKEN_MAX_TTL
