apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: vault
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://helm.releases.hashicorp.com
    chart: vault
    targetRevision: 0.29.1
    helm:
      values: |
        global:
          enabled: true
          tlsDisable: false
        injector:
          enabled: false
        server:
          standalone:
            enabled: true
            config: |
              ui  = true

              listener "tcp" {
                address = "[::]:8200"
                cluster_address = "[::]:8201"
                tls_cert_file = "/vault/userconfig/tls/tls.crt"
                tls_key_file = "/vault/userconfig/tls/tls.key"
              }

              storage "file" {
                path = "/vault/data"
              }
          nodeSelector:
            node-role.kubernetes.io/master: "true"
          volumes:
            - name: tls
              secret:
                secretName: vault-tls
          volumeMounts:
            - mountPath: /vault/userconfig/tls
              name: tls
              readOnly: true
          dataStorage:
            enabled: true
            size: 10Gi
          readinessProbe:
            enabled: true
            path: "/v1/sys/health?standbyok=true&sealedcode=204&uninitcode=204"
          ingress:
            enabled: true
            ingressClassName: public
            annotations:
              nginx.ingress.kubernetes.io/backend-protocol: "HTTPS"
              cert-manager.io/cluster-issuer: default-issuer
            hosts:
              - host: vault.k8s.gastbob40.ovh
            tls:
              - hosts:
                  - vault.k8s.gastbob40.ovh
                secretName: vault-tls
  destination:
    namespace: vault
    name: in-cluster
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
